### PR TITLE
make tar extraction more Linux friendly

### PR DESCRIPTION
**Pull request by MichaelKorn**
Most people don't have 7z but tar will most likely be installed.

## Description

1. check if "tar" can be used
2. use "tar" if possible

## Motivation and Context
It should run with Linux

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by mpromonet** [comment]
Hi Michael,
Thanks for youre contribution.
The purpose to use 7z is to have the same command line between linux & windows.
I will prefer a cmake feature to uncompress like the DOWNLOAD one but it doesnot seems to exist, or I did not find how.
I like to keep the CMakeList.txt as simple as it could be, then I do not think to merge this.
Best regards,
Michel.

**Comment by MichaelKorn** [comment]
Hey Michel,
It is too bad that there is no general command for decompressing.
Most Linux Systems do not  have 7z pre installed. I had to look into the CMakeLists to understand the problem and it was easier/faster to change the command to tar.
Alternatively, we could check if 7z is available, if not there should be a clear message. Should I make a PR?
Regards,
Michael

**Comment by mpromonet** [comment]
Hi Michael,
In order to have a unique way to uncompress tar.gz, I update the CMakeList.txt using `cmake -E tar` in commit https://github.com/mpromonet/webrtc-streamer/commit/5e3cf01043ee3646a2af55392a432407f4afec27
This should avoid installation of 7z.
Best Regards,
Michel.

**Comment by MichaelKorn** [comment]
Thanks a lot!

**Pull request closed without merging**
