### PR TITLE
Properly detect webrtc build

### PR DESCRIPTION
**Pull request by 9a4gl**

### CODE REVIEW

**Comment by 9a4gl** [comment]
Still, when linking with debug version of webrtc I get:
Logger level:4
/usr/include/c++/5/debug/safe_iterator.h:167:error: attempt to initialize 
    an iterator that will immediately become singular.

Objects involved in the operation:
iterator "this" @ 0x0x2829110 {
  state = singular;
  references sequence @ 0x0x28290e8
}
fish: “./webrtc-streamer” terminated by signal SIGABRT (Abort)

**Comment by mpromonet** [comment]
Hi 9a4gl,
f your objects are still in out/Release/webrtc/obj, I guess you are using an old WebRTC release, maybe you should upgrade it.
However It's tru that I did not build often debug release, I will add it to travis build.
Regards,
Michel.

**Comment by 9a4gl** [comment]
I am using gclient sync -r branch-heads/61 .. guess 61 is the latest release.. never actually understand what master is, is it latest release, future release or ?
I had troubles compiling with master, that is why I changed to 61, and yup, that may be cause why I needed this change
so, would be actually good if webrtc-streamer could stick to some webrtc release, as I see quite often issues with compiling due to some changes and you never know whether you need to update webrtc, or wait for update of webrtc-streamer

**Comment by mpromonet** [comment]
Hi 9a4gl 
The lastest release I tried is 63, that doesnot build in debug, I raised a ticket to webrtc team https://bugs.chromium.org/p/webrtc/issues/detail?id=8465
Sticking to a WebRTC release is annoying, because lots of thing are moving, I prefer to make often little modifications than a lots of modification when I upgrade.
Anyway this project is experimental....
Best Regards,
Michel.

**Pull request closed without merging**
