### PR TITLE
Error parsing SPS when using TCP

### PR DESCRIPTION
**Pull request by 9a4gl**
#37

### CODE REVIEW

**Comment by mpromonet** [comment]
Hi Tihomir,
Thanks for this submission.
When i tried to parse the full buffer it fails, this is why the code skip the marker.
I Will check if current webrtc parse now correctly.
Best Regards,
Michel

**Comment by mpromonet** [comment]
Hi,
I tried your modification, but it doesnot works with the webrtc I used, I will update webRTC to see if it works.
Maybe I will use h264bitstream to parse SPS, as I did in an other project, see #20 
Best Regards,
Michel.

**Comment by 9a4gl** [comment]
I am using latest webrtc source.. my change works fine with all 8 of my camera (5 different types of cameras)

**Comment by 9a4gl** [comment]
Fix from #20 does not help in my case. With that fix and mine it works here.

**Comment by mpromonet** [comment]
Hi,
I check again with the last webrtc and with this Pull Request and it is not working with rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov.
Best Regards,
Michel.

**Comment by 9a4gl** [comment]
You can try rtsp:<slash><slash>webrtc:streamer@44.170.133.52:554<slash>0 using tcp
it should accessible from public

**Comment by mpromonet** [comment]
Hi,
Finally I replace WebRTC parsing of H264 buffer with h264bitstream that seems much more robust. 
Using this parser it works with your url and with the big bunny.
Best Regards,
Michel.

**Pull request closed without merging**
